version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - /srv/db_data:/var/lib/postgresql/data

  auth:
    build:
      context: ./auth
    ports:
      - "8080:8080"
    volumes:
      - /srv/photos:/srv/photos

  userapi:
    build:
      context: ./userApi
    ports:
      - "8081:8081"
